-- Step 1: Add new theme values to enum
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'DEFAULT';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'NORD';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'GOLD';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'NATURE';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'NETFLIX';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'LARACON';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'DRACULA';
